version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bloom-payment-gateway-service:prod
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-bloom_payment_gateway_prod}
      - JWT_ACCESS_TOKEN_PRIVATE_KEY=${JWT_ACCESS_TOKEN_PRIVATE_KEY}
      - JWT_ACCESS_TOKEN_PUBLIC_KEY=${JWT_ACCESS_TOKEN_PUBLIC_KEY}
      - JWT_REFRESH_TOKEN_PRIVATE_KEY=${JWT_REFRESH_TOKEN_PRIVATE_KEY}
      - JWT_REFRESH_TOKEN_PUBLIC_KEY=${JWT_REFRESH_TOKEN_PUBLIC_KEY}
      - GATEWAY_API_KEY=${GATEWAY_API_KEY}
      - FISERV_API_KEY=${FISERV_API_KEY}
      - FISERV_API_SECRET=${FISERV_API_SECRET}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - payment-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-bloom_payment_gateway_prod}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - payment-network

volumes:
  postgres_data_prod:

networks:
  payment-network:
    driver: bridge 