version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bloom-payment-gateway-service:uat
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=uat
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bloom_payment_gateway_uat
      - JWT_ACCESS_TOKEN_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKB\nvVXrz2VsbC44mR2Gr55hjlBGhh9kwm0nutEsR2mRjS2N51ry9CW0oAh3gqBObfN\n-----END PRIVATE KEY-----
      - JWT_ACCESS_TOKEN_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCgb1V689l\nbGwuOJkdhq+eYY5QRoYfZMJtJ7rRLEdpkY0tjedacvQltKAId4KgTm3zQjWF4x\n-----END PUBLIC KEY-----
      - JWT_REFRESH_TOKEN_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKB\nvVXrz2VsbC44mR2Gr55hjlBGhh9kwm0nutEsR2mRjS2N51ry9CW0oAh3gqBObfN\n-----END PRIVATE KEY-----
      - JWT_REFRESH_TOKEN_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCgb1V689l\nbGwuOJkdhq+eYY5QRoYfZMJtJ7rRLEdpkY0tjedacvQltKAId4KgTm3zQjWF4x\n-----END PUBLIC KEY-----
      - GATEWAY_API_KEY=${GATEWAY_API_KEY}
      - FISERV_API_KEY=${FISERV_API_KEY}
      - FISERV_API_SECRET=${FISERV_API_SECRET}
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - payment-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bloom_payment_gateway_uat
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_uat:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - payment-network

volumes:
  postgres_data_uat:

networks:
  payment-network:
    driver: bridge 